### ISSUE TITLE
Update keys location for ryujinx in guide

### ISSUE THREAD

**Issue by whitetigerx8** [EmuDeck/emudeck.github.io#33]
The guide neeeds to be updated to where you need to put the prod.keys file as the folder specified isn't found by ryujinx. I found the correct one under the file menu, choosing Open Ryujinx folder. It took me to Home\.config\Ryujinx\system, where I put the prod.keys file and now Ryujinx is able to find it when I restarted it.

**Comment by fromthyashes** [comment]
The `Emulation/bios/ryujinx/keys` directory, listed on the Cheat Sheet and Ryujinx page, is a symlink to the `/home/deck/.config/Ryujinx/system` directory. This isn't a documentation error, but may have been a broken symlink.
